// <auto-generated />
using System;
using Hotel_m.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotel_m.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Hotel_m.Models.Administrator_Db", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Administratori");
                });

            modelBuilder.Entity("Hotel_m.Models.Camera_Db", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Disponibilitate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Etaj")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Facilitati")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HotelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tip")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Camere");
                });

            modelBuilder.Entity("Hotel_m.Models.Client_Db", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NrTelefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Varsta")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("Hotel_m.Models.Hotel_Db", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Facilitati")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Locatie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Hoteluri");
                });

            modelBuilder.Entity("Hotel_m.Models.Plata_Db", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RezervareId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Suma")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tip")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RezervareId")
                        .IsUnique();

                    b.ToTable("Plati");
                });

            modelBuilder.Entity("Hotel_m.Models.Recenzie_Db", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comentariu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("HotelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("HotelId");

                    b.ToTable("Recenzii");
                });

            modelBuilder.Entity("Hotel_m.Models.Rezervare_Db", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CameraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCheckIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCheckOut")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PretTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("ClientId");

                    b.ToTable("Rezervari");
                });

            modelBuilder.Entity("Hotel_m.Models.Turist_Db", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CNP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RezervareId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RezervariId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Varsta")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RezervariId");

                    b.ToTable("Turisti");
                });

            modelBuilder.Entity("Hotel_m.Models.Camera_Db", b =>
                {
                    b.HasOne("Hotel_m.Models.Hotel_Db", "Hotel")
                        .WithMany("Camere")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Hotel_m.Models.Plata_Db", b =>
                {
                    b.HasOne("Hotel_m.Models.Rezervare_Db", "Rezervare")
                        .WithOne("Plata")
                        .HasForeignKey("Hotel_m.Models.Plata_Db", "RezervareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rezervare");
                });

            modelBuilder.Entity("Hotel_m.Models.Recenzie_Db", b =>
                {
                    b.HasOne("Hotel_m.Models.Client_Db", "Client")
                        .WithMany("Recenzii")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel_m.Models.Hotel_Db", "Hotel")
                        .WithMany("Recenzii")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Hotel_m.Models.Rezervare_Db", b =>
                {
                    b.HasOne("Hotel_m.Models.Camera_Db", "Camera")
                        .WithMany("Rezervari")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel_m.Models.Client_Db", "Client")
                        .WithMany("Rezervari")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Hotel_m.Models.Turist_Db", b =>
                {
                    b.HasOne("Hotel_m.Models.Rezervare_Db", "Rezervari")
                        .WithMany()
                        .HasForeignKey("RezervariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rezervari");
                });

            modelBuilder.Entity("Hotel_m.Models.Camera_Db", b =>
                {
                    b.Navigation("Rezervari");
                });

            modelBuilder.Entity("Hotel_m.Models.Client_Db", b =>
                {
                    b.Navigation("Recenzii");

                    b.Navigation("Rezervari");
                });

            modelBuilder.Entity("Hotel_m.Models.Hotel_Db", b =>
                {
                    b.Navigation("Camere");

                    b.Navigation("Recenzii");
                });

            modelBuilder.Entity("Hotel_m.Models.Rezervare_Db", b =>
                {
                    b.Navigation("Plata")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
